# Generated by Django 4.1a1 on 2022-10-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapapp", "0003_alter_search_arrival_alter_search_departure"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="color",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="hompage",
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="mapping",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="building",
            name="role",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
