# Generated by Django 4.1a1 on 2022-10-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapapp", "0004_building_color_building_hompage_building_mapping_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="prefix",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
