# Generated by Django 4.1a1 on 2022-10-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapapp", "0005_building_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="prefix",
            field=models.BooleanField(default=False),
        ),
    ]
