# Generated by Django 4.1a1 on 2022-10-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapapp", "0006_alter_building_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="hompage",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
