# Generated by Django 4.1a1 on 2022-10-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapapp", "0007_alter_building_hompage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mode", models.BooleanField(default=True)),
            ],
        ),
    ]
